### ISSUE TITLE
Reloaded : Chain stuff > memory leak

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#168]
the memory allocated by strdup seems to be never liberated

    for( i = 0; i < MAX_UI_PARAMETERS; i ++ )
    {
        snprintf(text,sizeof(text),"slider_p%d" , i );
        slider_names_[i].text = strdup( text );
        [....]

https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-client/src/vj-api.c#L7685

**Comment by c0ntrol** [comment]
Yes this has been like this since forever, the stuff in vj_gui_init is never freed (it is used throughtout the entire life cycle). The kernel will free the remaining memory when the application exits

You are welcome to fix this, but the ui was never properly refactored. There is a lot to improve there
