### ISSUE TITLE
fx : Matrix Dithering - param2 (Value - random_on) not used

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#38]
Into "Matrix Dithering" libvje (https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/effects/dither.c) the second parameter "int random_on" is not used.

maybe could be used like that ? (look at __random_offset__ variable)
```cpp
void dither_apply(VJFrame *frame, int width, int height, int size,
		  int random_on)
{
    long int w_, h_;
    long int dith[size][size];
    long int i, j, d, v, l, m;
    uint8_t *Y = frame->data[0];
    double random_offset;

    for (l = 0; l < size; l++) {
	for (m = 0; m < size; m++) {
		random_offset = random_on? rand() / (RAND_MAX + 1.0) : 1;
	        dith[l][m] =1 + (int) ((double) size * random_offset);
	}
    }

    for (h_ = 0; h_ < height; h_++) {
	j = h_ % size;
	for (w_ = 0; w_ < width; w_++) {
	    i = w_ % size;
	    d = dith[i][j] << 4;
	    /* Luminance , dither image. Do
	       this for U and V too, see what happens hehe */
	    v = ((long) Y[((h_ * width) + w_)] + d);
	    Y[(h_ * width) + w_] = (uint8_t) ((v >> 7) << 7);
	}
    }
}
```

Whats better is that a random value is used only when random is ON (and this should give "better performances") .... but unfortunately, visually speaking, when random is ON i do not see much differences...

**Comment by c0ntrol** [comment]
What is wrong with the FX parameter 'random_on' , is that it appears as beeing 'on' all the time because the dith[][] table is rebuild every frame. That should only happen when size changes

Performance wise most can be achieved by writing tree-vectorization friendly code for gcc but its a tidious process as described here: http://locklessinc.com/articles/vectorize/

If you want to do your suggested change (random_offset) that would be OK. I can add a mode parameter if we want to keep the old behaviour as well (this change should produce a different result for same values of size)

Another optimization might be to replace the random() function for a number generator, has to be visually inspected

**Comment by d-j-a-y** [comment]
yeah [now](https://github.com/c0ntrol/veejay/commit/efdb1961c7488d7e16daadfa6470f38f51ac222e) Matrix Dithering is nicer and cool with a working random parameter !

Do you know if it's possible to less line "artefact" on high p0 (why mode?) parameter  here 166 for a 800x600 ?
![matrixdithering_lines](https://cloud.githubusercontent.com/assets/2943058/10986206/50ca38f0-8428-11e5-9fa7-bd8bf16c1a22.png)

**Comment by c0ntrol** [comment]
The mode parameter defines the manner of calculating the matrix table; That's why I called it Mode, open for suggestions tho

No idea about the lines, the effect was written a long time ago. Perhaps it is due to small values in dith[][] 

 `d = dith[i][j] << 4;`
